name: Build and Deploy to Bintray

on:
  release:
    types: [created]
#  [push]

# Environment variables available to all jobs and steps in this workflow
env:
  BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
  BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish to Bintray
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Increase JAVA heap
        run: export _JAVA_OPTIONS="-Xmx2g"

      - name: Compile
        run: sbt compile

      - name: Publish with credentials
        run: sbt -Dbintray.user=$BINTRAY_USER -Dbintray.pass=$BINTRAY_PASS publish
